### ISSUE TITLE
Discover groups

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#513]
Seems like we don't have a special issue for Discover groups. If we have, please merge the issues @anjhero @anjesh @shresthaKiran .

According to your "reamining works" spread sheet this is done, but it's far from done.

You can’t see the letters Å Ä and Ö and it's still wrong when you press them: you get referred to the start of the list instead of the letter you chosen.

When you press the map, the map avatars are white like this: 
![photo_2018-08-26_17-52-44](https://user-images.githubusercontent.com/10048880/44630099-dcb70c00-a958-11e8-8b75-73cbaaf85681.jpg)

Looks weird right? Use the same pink map as we use for everything else instead, if no group photo.

Designwise, the purple GPS dot in the map should be pulsing, as everywhere else it should be pulsing.

**Comment by MattiasJay** [comment]
This is the same error as the sentence above from August 26 2018: "...it's still wrong when you press them: you get referred to the start of the list instead of the letter you chosen." @ruchidhami

**Comment by ruchidhami** [comment]
This has been resolved now.

**Comment by MattiasJay** [comment]
Good work with this @ruchidhami !

This has proven to be tricky, as we understand. Still, not all groups are seen on the world map when zooming out in group map on Discover groups, so this issue remains open:

![photo_2019-04-04_12-21-00](https://user-images.githubusercontent.com/10048880/55548641-309a8800-56d4-11e9-9f78-9d40a3cb1cf3.jpg)

**Comment by umuieme** [comment]
@MattiasJay There are large number of groups in Sweden around 3000. When showing all those groups the map screen lags and groups overlaps as in the screenshot above. So how should we proceed with this?

**Comment by MattiasJay** [comment]
Hi again @umuieme ! Can you clarify this sentence "There are large number of groups in Sweden around 3000" ?

I suggest that we make a bundle for groups that overlap, like we did on the old webpage: http://old.skjutsgruppen.nu/search

In short; a bundle can be the same shape as the white place holders above (the "balloons") but another color and with the number of groups this bundle contains. The color can be the standard grey we use, and a white number.

when this grey bundle is pressed this bundle opens a page like below. Obviously not the same, but same standard design. This is just a screenshot from the "alphabetic order" view in "Discover groups" 😄 

![photo_2019-05-02_19-11-23](https://user-images.githubusercontent.com/10048880/57093410-1e7d2b00-6d0e-11e9-998c-3902e9e25f6f.jpg)

What do you think of this? Please come with suggestions on improvements.

**Comment by umuieme** [comment]
@MattiasJay When someone loads a map of Sweden there will be around 3000 markers in the map in very low place.
In the old skjutsgruppen, I could not find a way to make it working. Also if we are to bundle them we need some standard to bundle them in one. 
Can you please give more concrete example in how to bundle them?

**Comment by MattiasJay** [comment]
Hi again, just so I understand, when you say "3000 markers" do you mean names of places, villages and cities in Sweden? Or what are these markers?

I suggest that the bundle would be for groups that are in the exact same geographical location, @umuieme .

**Comment by umuieme** [comment]
Can you provide ui for bundling the groups.

**Comment by MattiasJay** [comment]
Here's the design @umuieme : 

1) Grey bundle bubble. In this example there are more than 99 groups in the same place so hence it says 99+ . The design fits all the numbers from 2 to 99. After 99 it should say 99+.

![2019_discover_groups_map](https://user-images.githubusercontent.com/10048880/57586967-edff7300-74fd-11e9-91e2-c483e8470734.jpg)

2) when clicking the bundle this page opens

![bundle](https://user-images.githubusercontent.com/10048880/57586973-01aad980-74fe-11e9-92cb-694c53b5533b.jpg)

All the designs and the vector for the grey bundle is on the Drive. Looking forward to see it implemented. Do you need any more design for this that I've missed @umuieme ?

**Comment by anjesh** [comment]
This appears to be a tweaked feature which we did not anticipate. @umuieme  was referring to bundling the points in this [sense](https://github.com/novalabio/react-native-maps-super-cluster-example/blob/master/assets/demo.gif). Your approach will be a new feature for us as we will have to develop the module ourselves and will take few days of work. What do you think of this [approach](https://github.com/novalabio/react-native-maps-super-cluster-example/blob/master/assets/demo.gif)?

**Comment by MattiasJay** [comment]
Ah I see @umuieme @anjesh . This may do the trick as well. 
1. If I understand correctly, this approach depends on zooming in the map. Correct?
2. How do this solve the problem with groups being in the exact same spot? (that was what I tried to solve with the above bundle design). We have this same "flickering" problem with rides being on the exact same spot so they overlay each other, see the world map in the start feed.

**Comment by anjesh** [comment]
> If I understand correctly, this approach depends on zooming in the map. Correct?

That's correct

> How do this solve the problem with groups being in the exact same spot? (that was what I tried to solve with the above bundle design). We have this same "flickering" problem with rides being on the exact same spot so they overlay each other, see the world map in the start feed.

This will remain as it is. Above feature will make the map screen fast, but flicker will remain when there are rides on exact same spot. This will take time and i think we need to put this under enhancement. But we will implement this [process](https://github.com/novalabio/react-native-maps-super-cluster-example/blob/master/assets/demo.gif).

**Comment by MattiasJay** [comment]
Proceed. Use the grey in above design in the cluster bubbles to keep in line with our design profile. @anjesh @anjhero @umuieme

**Comment by ruchidhami** [comment]
Hi! @MattiasJay , This has been pushed . If there needs to change any thing please comment.

**Comment by MattiasJay** [comment]
Example; zooming in Gothenburg. There's 23 groups here I can't access or see:

![GitHawk Upload by MattiasJay](https://i.imgur.com/iX3tzyG.jpg)

**Comment by umuieme** [comment]
@MattiasJay Those 23 groups are in exact same coordinates. That's why zoom has no effect on them. If you click in the 23, it will redirect you to the search screen with the source and destination prefilled and group filter selected from where you can proceed to see the group search result screen.

**Comment by MattiasJay** [comment]
Thanks for your work @umuieme . This is unintuative when we are testing this right now, so we will keep this issue open for further development. 

**Notes for further development:**
- See the preferred design above for view when pressing a grey place holder containing groups that are on the exact same spot (we have many of those).
